version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  groups:
    all-nuget-packages:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: "/" # checks in .github/workflows
  schedule:
    interval: monthly
